### ISSUE TITLE
Refactor into multiple modules

### ISSUE THREAD

**Issue by TimJentzsch** [edouardpoitras/bevy_local_commands#16]
I'm starting to feel like the single `lib.rs` file doesn't scale anymore.
I think we should start to split of some code into separate modules.

Some candidates are for example the `Process` component, maybe also the `LocalCommand` component (worth it after #15) and probably the process spawning logic.

If we want to keep simple imports for the user, we can consider to use reexports (`pub use`) and/or to add a `prelude` similar to Bevy.

**Comment by edouardpoitras** [comment]
Agreed. No preference in terms of imports.
