### ISSUE TITLE
Pass exit status instead of success in `ProcessCompleted`

### ISSUE THREAD

**Issue by TimJentzsch** [edouardpoitras/bevy_local_commands#18]
In the `ProcessCompleted` event, we currently just pass a bool whether the command succeeded or not.
However, some users might also need the exit status that the process returned.

We can replace `success: bool` with `exit_status: ExitStatus`.
The user can then still obtain the previous value with `exit_status.success()`.

**Comment by edouardpoitras** [comment]
Good call. Sounds like the right move.
