### ISSUE TITLE
Sending input to the processes

### ISSUE THREAD

**Issue by TimJentzsch** [edouardpoitras/bevy_local_commands#2]
It would be nice if I could not only receive the output of the process, but also provide it with input by writing to its output channels.
So basically like simulating the user writing lines into the console.

Some processes, like VS Code language servers and UCI chess engines are long running and communicate entirely over stdin/stdout, so this feature would unlock additional use cases for the plugin.

**Comment by edouardpoitras** [comment]
I like the idea. This will require some thought as I don't think `duct` supports input capabilities.

Edit: This blog post has an example using std::process::Command: https://www.nikbrendler.com/rust-process-communication/
