### ISSUE TITLE
Add add-on to retry a command if it failed

### ISSUE THREAD

**Issue by TimJentzsch** [edouardpoitras/bevy_local_commands#20]
Add a new component which can be inserted along with `LocalCommand`.
If present, it should automatically spawn a command again if it failed (i.e. exit status is not success).

We can offer multiple options, such as maximum number of retries, delay between restarts, etc.

**Comment by edouardpoitras** [comment]
I started working on this but realized that it's quite a bit more complicated than initially thought.

For one, there's no clear way of "restarting" the execution of a process.
As far as I can tell, we would need to keep track of the command that was run, the environment variables, and the arguments throughout the lifecycle of the process. Then a failed ProcessCompleted event would result in the following:
- Retry checks (do we retry or are we done yet)
- If retrying, remove the Process component, and replace the LocalCommand component
- The next system run will spawn the process and attach the Process component again

Of course this means that the process ID changes which could make our users a bit unhappy.

It's also unclear how to deal with the Cleanup addon. I don't know how to decouple those two addons effectively (the logic of one would need to take into account the other) - which sort of defeats the purpose of "addons" and puts them both more in the realm of core library code.

The more I think about it, the more I'm leaning on letting the users do their own retry logic.

@TimJentzsch am I missing something here? Any thoughts?

**Comment by TimJentzsch** [comment]
I think we store the `std::process::Command` in `LocalCommand`, I thought that its possible to simply execute that again. But maybe that's not possible.

For the coupling I agree, Im not sure if that can be avoided...

**Comment by edouardpoitras** [comment]
Ah yes you're right, I came back to correct myself - LocalCommand component can be used to retrieve the command details. I will think on it a bit more.

**Comment by edouardpoitras** [comment]
My first attempt is posted in PR #30 .
Still a few limitations I'd like to eventually tackle (backoff strategy, retry delay, and compatibility with Cleanup).
