### ISSUE TITLE
Add add-on for clean-up after command completion

### ISSUE THREAD

**Issue by TimJentzsch** [edouardpoitras/bevy_local_commands#22]
Add a new add-on which handles cleanup of completed processes.
If added, it should despawn the entity of the process.

Later on, we can also add different options, like only removing the `Process` component, in case that the user has other components on the entity which they still need.

There is a bit of a trade-off here, having this in a separate component.
I assume that in most cases it is the desired behavior, so the user would often need to add this component.
However, I think it offers a nice consistency if add-on functionality is additive, i.e. we only add new functionality and don't remove stuff that already exists.

**Comment by edouardpoitras** [comment]
I have a working implementation of this, just waiting on #16 to be merged in.
