### ISSUE TITLE
Add to Bevy Assets page

### ISSUE THREAD

**Issue by TimJentzsch** [edouardpoitras/bevy_local_commands#23]
To help people find this plugin, we should add an entry to the [Bevy Assets page](https://bevyengine.org/assets/).
This can be done on the [`bevy-assets`](https://github.com/bevyengine/bevy-assets) repository.

Bonus points if we can create some kind of logo / image to stand out a bit more.
Maybe an icon like `> _` to represent a command line? Creativity is not my strong suite :D

**Comment by edouardpoitras** [comment]
We have that in common - hence my profile icon :)
Thankfully, we have LLMs now.
![icon](https://github.com/edouardpoitras/bevy_local_commands/assets/14075649/3b909677-f5f1-4f09-b081-22b9d8200619)
What do you think of that one?

**Comment by TimJentzsch** [comment]
Good enough for me :D

Maybe we should make the corners transparent to better fit into the Bevy Asset cards.

**Comment by edouardpoitras** [comment]
New PR: https://github.com/bevyengine/bevy-assets/pull/400

Added to the Helpers section - couldn't really find a good fit elsewhere...

**Comment by edouardpoitras** [comment]
Done: https://bevyengine.org/assets/#helpers

**Comment by TimJentzsch** [comment]
Awesome, nice to see!
