### ISSUE TITLE
Update to Bevy 0.12

### ISSUE THREAD

**Issue by TimJentzsch** [edouardpoitras/bevy_local_commands#3]
Converting this to an issue so it's easier to reference in PRs.

We should update Bevy to the latest version (v0.12) and fix all issues that come up.

**Comment by edouardpoitras** [comment]
Turns out this was just a matter of updating the bevy dependency. Now in main branch.

We can keep working off of main and I'll port back any changes to a v0.11 branch manually as I'm stuck on 0.11 until some other dependencies upgrade as well.
