### ISSUE TITLE
ERROR: Input redirection is not supported, exiting the process immediately.

### ISSUE THREAD

**Issue by edouardpoitras** [edouardpoitras/bevy_local_commands#31]
Getting the following output when running the simple example in Windows 10:
```
PS C:\bevy_local_commands> cargo run --example simple
    Finished dev [unoptimized + debuginfo] target(s) in 2.76s
     Running `target\debug\examples\simple.exe`
Spawned the command as entity 0v0
Output Line (0v0): Sleeping for 1s
ERROR: Input redirection is not supported, exiting the process immediately.
Command 0v0 completed (Success - false)
```

The same error occurs for every example. I don't recall this happening last time I ran the examples in Windows.

We need to setup a build pipeline for all 3 major operating systems.

**Comment by TimJentzsch** [comment]
From what I could find online, this appears to be connected to the `timeout` command in Windows.

The really hacky workaround seems to be to use the `ping` command to a non-existant address with a delay defined... <https://serverfault.com/questions/432322/how-to-sleep-in-a-batch-file/613296#613296>

But that seems aweful for example code

**Comment by edouardpoitras** [comment]
Confirmed.
I think we can safely use the `powershell` command instead of the `cmd` command.
It has sleep and echo keywords which behave the same as the unix ones.
Pretty sure Powershell is accessible for devices on Windows 7 and up. Any objections?

**Comment by TimJentzsch** [comment]
Sounds good to me!
